volumes:
  prometheus_data: {}
  grafana_data: {}
  dashboards: {}

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: "avalanchego-machine"
          static_configs:
            - targets: ["localhost:9100"]
              labels:
                alias: "machine"
        - job_name: "avalanchego"
          metrics_path: "/ext/metrics"
          static_configs:
            - targets: ["localhost:9650"]

  grafana_datasources:
    content: |
      apiVersion: 1
      
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://localhost:9090
          isDefault: true
          version: 1
          editable: false

  grafana_dashboards_provider:
    content: |
      apiVersion: 1
      
      providers:
        - name: "Avalanche"
          orgId: 1
          folder: ""
          folderUid: ""
          type: file
          disableDeletion: false
          updateIntervalSeconds: 30
          allowUiUpdates: true
          options:
            path: /etc/grafana/dashboards
            foldersFromFilesStructure: true

services:
  dashboards_downloader:
    image: alpine:latest
    container_name: dashboards_downloader
    restart: on-failure
    volumes:
      - dashboards:/dashboards
    command:
      - 'sh'
      - '-c'
      - |
        apk add --no-cache wget unzip
        cd /tmp
        if [ -z "$(ls -A /dashboards)" ]; then
          echo "Downloading dashboards..."
          wget -q https://github.com/ava-labs/avalanche-monitoring/archive/refs/heads/main.zip
          unzip -q main.zip
          cp avalanche-monitoring-main/grafana/dashboards/*.json /dashboards/
          echo "Dashboards downloaded and extracted"
        else
          echo "Dashboards already exist, skipping download"
        fi

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=127.0.0.1:9100'
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=127.0.0.1:9090'
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - dashboards:/etc/grafana/dashboards:ro
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards_provider
        target: /etc/grafana/provisioning/dashboards/avalanche.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_ADDR=127.0.0.1
    depends_on:
      prometheus:
        condition: service_started
    network_mode: host  
